classdef g009a < model
    %% Example linear system, taken from
    % Krysander, M., Aslund, J., & Frisk, E. (2010).
    % A Structural Algorithm for Finding Testable Sub-models and Multiple Fault Isolability Analysis
    % 21st International Workshop on the Principles of Diagnosis.
    
    % x1dot = -xi + u + f1
    % x2dot = x1 - 2*x2 + x3 + f2
    % x3dot = x2 -3*x3
    % y1 = x2 + f3
    % y2 = x2 + f4
    % y3 = x3 + f5
    
    methods
        function this = g009a()
            this.name = 'g009a';
            this.description = 'Linear system found in "A Structural Algorithm for Finding Testable Sub-models and Multiple Fault Isolability Analysis"';
            
            con = [...
                {'fault x1_dot x1 inp u'};...
                {'fault x2_dot x1 x2 x3'};...
                {'x3_dot x2 x3'};...
                ];
            
            der = [...
                {'int x1 dot x1_dot'};... % x1_dot is the derivative of x1
                {'int x2 dot x2_dot'};...
                {'int x3 dot x3_dot'};...
                ];
            
            msr = [...
                {'fault msr y1 x2'};...
                {'fault msr y2 x2'};...
                {'fault msr y3 x3'};...
                ];
            
            this.constraints = [...
                {con},{'c'};...
                {der},{'d'};...
                {msr},{'s'};...
                ];
            
            this.coordinates = [];
            
        end
        
    end
    
end
