classdef g036 < model
    
    methods
        function this = g036()
            this.name = 'g036';
            this.description = 'Demonstration model, to showcase marking of offensive edges in dynamic loops containing AEs';
            
            %% Equation list
            % legend:
            % dot - differential relation
            % int - integral term
            % trig - trigonometric term
            % ni - general non-invertible term
            % inp - input variable
            % out - output variable % NOT SUPPORTED
            % msr - measured variable
            % sub - subsystem where the equation belongs
            kin = [...
                {'x_1 x_3'};...
                {'fault x_3 ni dx_1 x_2'};...
                {'x_3 x_2'};...
                {'x_2 ni x_4'};...
                {'x_4'};...
                ];
            
            der = [...
                {'int dx_1 dot x_1'};...
                ];
            
            dyn = [...
                ];
            % Set non-zero V, u
            
            msr = [...
                ];
            
            this.constraints = [...
                {kin},{'k'};...
                {der},{'d'};...
                {dyn},{'f'};...
                {msr},{'s'};...
                ];            
        end
        
    end
    
end