classdef g024 < model

% The model equations are taken from Fault Diagnosis Toolbox
% 
% Aguilera, F., et al. "Current-sensor fault detection and isolation 
% for induction-motor drives using a geometric approach." 
% Control Engineering Practice 53 (2016): 35-46.

    methods
        function this = g024()
            this.name = 'g024';
            this.description = 'Induction Motor, taken from Fault Diagnosis Toolbox';
            
            con = [...
                {'q_a w lambda_a'};...
                {'q_b w lambda_b'};...
                {'di_a i_a lambda_a q_b msr u_a'};...
                {'di_b i_b lambda_b q_a msr u_b'};...
                {'dlambda_a i_a lambda_a q_b'};...
                {'dlambda_b i_b lambda_b q_a'};...
                {'dw w i_a lambda_b i_b lambda_a Tl'};...
                ];
            
            der = [...
                {'int di_a dot i_a'};...
                {'int di_b dot i_b'};...
                {'int dlambda_a dot lambda_a'};...
                {'int dlambda_b dot lambda_b'};...
                ];
            
            msr = [...
                {'fault msr y1 i_a'};...
                {'fault msr y2 i_b'};...
                {'msr y3 w'};...
                ];
                
            this.constraints = [...
                {con},{'c'};...
                {der},{'d'};...
                {msr},{'s'};...
                ];
            
            this.coordinates = [];
            
        end
        
    end
    
end