function [ ] = plotIM( IMStruct, varargin )
%PLOTIM Plot Isolability Matrix Struct
%   INPUTS:
%   IMStruct: Isolation Matrix Structure, as generated by generateIM()
%   varargin: Rest of the arguments, see inputParse below

p = inputParser;
p.addOptional('permute',true); % Permute matrix for clarity
p.parse( varargin{:} );
opts = p.Results;

numFaults = length(IMStruct.fault_ids);

% Permute the IM if required
if opts.permute
    [p,q] = dmperm(IMStruct.IM);
else
    p = 1:numFaults;
    q = p;
end

spy(IMStruct.IM(p,q))

set(gca,'XTick', 1:numFaults);
set(gca,'YTick', 1:numFaults);

set(gca,'XTickLabel', IMStruct.fault_aliases(p));
set(gca,'YTickLabel', IMStruct.fault_aliases(p));
xtickangle(90);

xlabel('')

title('Isolability Matrix');

end

