classdef g025 < model
% Benchmark model Raghuraj-1 from Fault Diagnosis Toolbox
%  From "Locating sensors in complex chemical plants based on fault 
%  diagnostic observability criteria" by Rao Raghuraj, Mani Bhushan, 
%  and Raghunathan Rengaswamy, Volume 45, Issue 2, 
%  Pages 310 - 322, AIChE.

    methods
        function this = g025()
            this.name = 'g025';
            this.description = 'Benchmark model Raghuraj-1 from Fault Diagnosis Toolbox';
            
            con = [...
                {'x14 x15 x20 x21 xf13'}; ...
                {'fault x15 x19 x20 x21 xf13'}; ...
                {'x15 x16 x17 x18 xf1 xf2'}; ...
                {'fault x17'}; ...
                {'fault x18'}; ...
                {'x17 x18 x19 xf1 xf2'}; ...
                {'fault x20 x21 xf13'}; ...
                {'fault x21 x22 xf13'}; ...
                {'fault x22 x23 x24'}; ...
                {'fault x23'}; ...
                {'x21 x24'}; ...
                {'fault xf1'}; ...
                {'fault xf2'}; ...
                {'fault xf13'};...
                ];
            
            msr = [...
                {'msr zx15 x15'};...
                {'msr zx17 x17'};...
                {'msr zx18 x18'};...
                {'msr zx19 x19'};...
                {'msr zx20 x20'};...
                {'msr zx21 x21'};...
                {'msr zx23 x23'};...
                ];
                
            this.constraints = [...
                {con},{'c'};...
                {msr},{'s'};...
                ];
            
            this.coordinates = [];
            
        end
        
    end
    
end