classdef g032 < model
    
    methods
        function this = g032()
            this.name = 'g032';
            this.description = 'Fixed-wing UAV submodel, to test AoS fault response';
            
            %% Equation list
            % legend:
            % dot - differential relation
            % int - integral term
            % trig - trigonometric term
            % ni - general non-invertible term
            % inp - input variable
            % out - output variable % NOT SUPPORTED
            % msr - measured variable
            % sub - subsystem where the equation belongs
            kin = [...
                {'Beta v Va expr -v+sin(Beta)*Va'};...
                ];
            
            der = [...
                {'int dot_v dot v expr differentiator'};...
                ];
            
            dyn = [...
                {'dot_v r ni u ni p ni w Fy par m expr -dot_v+r*u+p*w+Fy/m'};...
                ];
            % Set non-zero V, u
            
            msr = [...
                {'fault Beta msr Beta_m expr -Beta+Beta_m'};...
                {'fault msr Va_m Va expr -Va+Va_m'};...
                {'msr r_m r expr -r+r_m'};...
                {'msr p_m p expr -p+p_m'};...
                {'msr u_m u expr -u+u_m'};...
                {'msr w_m w expr -w+w_m'};...
                {'fault msr Phi_m Phi expr -Phi+Phi_m'};...
                {'fault msr Theta_m Theta expr -Theta+Theta_m'};...
                {'msr a_m_y Fy ni par m par g Phi ni Theta sub sensors expr -a_m_y+Fy/m-sin(Phi)*cos(Theta)*g'};...
                ];
            
            this.constraints = [...
                {kin},{'k'};...
                {der},{'d'};...
                {dyn},{'f'};...
                {msr},{'s'};...
                ];            
        end
        
    end
    
end