function [ IMStruct ] = generateIM( gi, FSStruct )
%GENERATEIM Generate Isolation Matrix
%   INPUTS:
%   gi      : The initial graph interface
%   FSStruct: Fault Signature Structure, as generated by generateFSM()

% Calculate the isolability matrix
numFaults = length(FSStruct.fault_ids);
numRes = length(FSStruct.residual_constraints);
IM = ones( numFaults, numFaults );

FSM=FSStruct.FSM;
for i=1:numRes
    % For each residual you can decouple those faults which are raised from
    % those faults which are not raised
    IM(FSM(i,:)>0,FSM(i,:)==0)=0;
end

% Get all the fault ids and aliases
fault_ids = gi.getVarIdByProperty('isFault');
fault_aliases = gi.getAliasById(fault_ids);

% Build the output
IMStruct.IM = IM;
IMStruct.fault_ids = fault_ids;
IMStruct.fault_aliases = fault_aliases;

end

