classdef g032a < model
    
    methods
        function this = g032a()
            this.name = 'g032a';
            this.description = 'Fixed-wing UAV submodel, to test AoS fault response. Includes wind estimates';
            
            %% Equation list
            % legend:
            % dot - differential relation
            % int - integral term
            % trig - trigonometric term
            % ni - general non-invertible term
            % inp - input variable
            % out - output variable % NOT SUPPORTED
            % msr - measured variable
            % sub - subsystem where the equation belongs
            kin = [...
                {'v v_r v_w expr -v+v_r+v_w'};...
                {'Beta v_r Va expr -v_r+sin(Beta)*Va'};...
                ];
            
            der = [...
                {'int dot_v dot v expr differentiator'};...
                ];
            
            dyn = [...
                {'dot_v r ni u ni p ni w Fy par m expr -dot_v+r*u+p*w+Fy/m'};...
                ];
            % Set non-zero V, u
            
            msr = [...
                {'fault Beta msr Beta_m expr equal'};...
                {'fault msr Va_m Va expr equal'};...
                {'msr r_m r expr equal'};...
                {'msr p_m p expr equal'};...
                {'msr u_m u expr equal'};...
                {'msr w_m w expr equal'};...
                {'fault msr Phi_m Phi expr equal'};...
                {'fault msr Theta_m Theta expr equal'};...
                {'msr a_m_y Fy ni par m par g Phi ni Theta sub sensors expr -a_m_y+Fy/m-sin(Phi)*cos(Theta)*g'};...
                {'msr v_w_m v_w expr equal'};...
                ];
            
            this.constraints = [...
                {kin},{'k'};...
                {der},{'d'};...
                {dyn},{'f'};...
                {msr},{'s'};...
                ];            
        end
        
    end
    
end