classdef g014 < model
    %% Structural Model Creation
    % Fixed Wing UAV
    methods
        function this = g014()
            this.name = 'g014';
            this.description = 'Fixed-wing UAV model';
            
            %% Equation list
            % legend:
            % dot - differential relation
            % int - integral term
            % trig - trigonometric term
            % ni - general non-invertible term
            % inp - input variable
            % out - output variable % NOT SUPPORTED
            % msr - measured variable
            
            %% Kinematic Equations
            
            % Position derivatives
            kin = [...
                {'Dnorth ni phi ni theta ni psi u v w'};...
                {'Deast ni phi ni theta ni psi u v w'};...
                {'Ddown ni phi ni theta ni psi u v w'};
                {'chi Deast Dnorth'};... % Course angle
                ];
            
            der = [...
                {'int Dnorth dot north'};...
                {'int Deast dot east'};...
                {'int Ddown dot down'};
                ];
            
            % Euler angle derivatives
            kin = [kin;...
                {'Dphi ni phi ni theta p q r'};...
                {'Dtheta ni phi q r'};...
                {'Dpsi ni phi ni theta q r'}
                ];
            
            der = [der;...
                {'int Dphi dot phi'};...
                {'int Dtheta dot theta'};...
                {'int Dpsi dot psi'};...
                ];
            
            % Angular Velocity
            kin = [kin;...
                {'fault Dp Γ ni Jxz ni Jx ni Jy ni Jz p q r Tx Tz'};...
                {'fault Dq ni Jy ni Jz ni Jxz p r Ty'};...
                {'fault Dr Γ ni Jx ni Jy ni Jz Jxz p q r Tx Tz'};...
                {'fault Γ Jx Jz Jxz'};...
                ];
            
            der = [der;...
                {'int Dp dot p'};...
                {'int Dq dot q'};...
                {'int Dr dot r'};...
                ];
            
            % Linear Velocity
            kin = [kin;...
                {'Du v w r q Fx m'};...
                {'Dv u w p r Fy m'};...
                {'Dw u v p q Fz m'};...
                ];
            
            der = [der;...
                {'int Du dot u'};...
                {'int Dv dot v'};...
                {'int Dw dot w'};...
                ];
            
            % Air data
            kin = [kin;...
                {'ur u uw'};...
                {'vr v vw'};...
                {'wr w ww'};...
                {'ww'};... %Assumption ww = 0;
                {'alpha wr ur'};...
                {'beta ur Va'};...
                {'Va ni ur ni vr ni wr'};...
                ];
            
            % Mass Distribution
            kin = [kin;...
                {'m mnom merr'};...
                {'pcgx m perrx merr'};...
                {'pcgy m perry merr'};...
                {'pcgz m perrz merr'};...
                {'merr'};... % merr = 0;
                ];
            
            %% Dynamic Equations
            dyn = [];
            
            dyn = [dyn;...
                {'Fx Fgx Fax Ftx'};...
                {'Fy Fgy Fay Fty'};...
                {'Fz Fgz Faz Ftz'};...
                {'Tx Tax Ttx'};...
                {'Ty Tay Tty'};...
                {'Tz Taz Ttz'};...
                ];
            
            % Gravity
            dyn = [dyn;...
                {'Fgx theta m g'};...
                {'Fgy phi theta m g'};...
                {'Fgz phi theta m g'};...
                ];
            
            % Aerodynamics
            dyn = [dyn;...
                {'Fax ni alpha ni beta FD FY FL'};...
                {'Fay ni beta FD FY'};...
                {'Faz ni alpha ni beta FD FY FL'};...
                {'Taxt Ttaxt pcgy pcgz pcly pclz Fay Faz'};...
                {'Tayt Ttayt pcgx pcgz pclx pclz Fax Faz'};...
                {'Tazt Ttazt pcgx pcgy pclx pcly Fax Fay'};...
                {'qbar rho Va'};...
                {'fault FD qbar S CD'};...
                {'fault FY qbar S CY'};...
                {'fault FL qbar S CL'};...
                {'fault Tax qbar S b Cl'};...
                {'fault Tay qbar S c Cm'};...
                {'fault Taz qbar S b Cn'};...
                {'fault CD ni Va ni alpha ni q inp deltae'};...
                {'fault CY ni Va ni beta ni p ni r inp deltaa inp deltar'};...
                {'fault CL ni Va ni alpha ni ni q inp deltae'};...
                {'fault Cl ni Va ni beta ni p ni r inp deltaa inp deltar'};...
                {'fault Cm ni Va ni alpha ni q inp deltae'};...
                {'fault Cn ni Va ni beta ni p ni r inp deltaa inp deltar'};...
                ];
            
            % Propeller
            dyn = [dyn;...
                {'fault Fty'};...
                {'fault Ftz'};...
                {'Ttxt Ttx pcgy pcgz ppry pprz Ftx Ftz'};...
                {'Ttyt Tty pcgx pcgz pprx pprz Ftx Ftz'};...
                {'Ttzt Ttz pcgx pcgy pprx ppry Ftx Fty'};...
                {'fault Tty'};...
                {'fault Ttz'};...
                {'fault Ftx CT rho n'};...
                {'fault CT ni Jar'};...
                {'Jar Va n'};...
                {'fault Pp Cp rho n'};...
                {'fault Cp ni Jar'};...
                {'fault Dn Pe Pp n'};...
                {'Ttx Pp n'};...
                ];
            
            der = [der;...
                {'int Dn dot n'};...
                ];
            
            % Motor
            dyn = [dyn;...
                {'fault n Kv Ei'};...
                {'fault Ei Vin Im Rm'};...
                {'Pe Ei Ii'};...
                {'fault Ii Im Io Ei R1'};...
                {'Pin Vin Im'};...
                {'fault Vin Vbat Io Rbat Rs inp deltat'};...
                ];
            
            %% Other models
            
            mod = [];
            
            mod = [mod;...
                {'H down'};... % geopotential altitude
                {'temp temp0 H H0'};... % Temperature gradient
                {'P P0 temp0 temp'};... % Pressure gradient
                {'rho P temp'};... % density gradient
                {'Pt P rho Va'};... % dynamic pressure
                {'g msr g0'};...
                ];
            
            %% Sensory equations
            
            msr = [];
            
            msr = [msr;...
                {'fault msr amx Fx m g theta'};... % Acceleration
                {'fault msr amy Fy m g phi theta'};...
                {'fault msr amz Fz m g phi theta'};...
                {'fault msr pm p'};... % Angular velocity
                {'fault msr qm q'};...
                {'fault msr rm r'};...
                {'fault msr hmx hx'};... % Magnetic field
                {'fault msr hmy hy'};...
                {'fault msr hmz hz'};...
                {'fault msr phim phi'};... % Euler angles
                {'fault msr thetam theta'};...
                {'fault msr psim psi'};...
                {'fault msr northm north'};... % GPS measurements
                {'fault msr eastm east'};...
                {'fault msr downm down'};...
                {'fault msr Dnorthm Dnorth'};...
                {'fault msr Deastm Deast'};...
                {'fault msr chim chi'};...
                {'fault msr temp0m temp0'};... % Initialization temperature
                {'fault msr H0m H0'};... % Initialization altitude
                {'fault msr Pm P'};... % Barometer reading
                {'fault msr tempm temp'};... % Therometer reading
                {'fault msr Ptm Pt'};... % Pitot reading
                {'fault msr alpham alpha'};.... % AoA reading
                {'fault msr betam beta'};... % AoS reading
                {'fault msr downml down'};... % Range finder reading
                {'fault msr Vbatm Vbat Io Rbat'};... % Battery voltage measurement
                {'fault msr Iom Io'};... % Battery current measurement
                {'fault msr nm n'};... % Motor rps measurement
                ];
            
            
            %% Summing up
            this.constraints = [...
                {kin},{'k'};...
                {dyn},{'f'};...
                {der},{'d'};...
                {mod},{'m'};...
                {msr},{'s'};...
                ];
            
            this.coordinates = [];
            
        end
        
    end
    
end
