classdef g024a < model

% Aguilera, F., et al. "Current-sensor fault detection and isolation 
% for induction-motor drives using a geometric approach." 
% Control Engineering Practice 53 (2016): 35-46.

    methods
        function this = g024a()
            this.name = 'g024a';
            this.description = 'Induction Motor, taken from Current-sensor fault detection and isolation for induction-motor drives using a geometric approach';
            
            %   di_a == -a*i_a + b*c*lambda_a + b*q_b+d*u_a,...
            %   di_b == -a*i_b + b*c*lambda_b + b*q_a+d*u_b,...
            %   dlambda_a == L_M*c*i_a - c*lambda_a-w*lambda_b, ...
            %   dlambda_b == L_M*c*i_b - c*lambda_b-w*lambda_a, ...
            %   dw == -k*c_f*w + k*c_t*(i_a*lambda_b - i_b*lambda_a) - k*Tl,...
            
            con = [...
                {'di_a i_a lambda_a lambda_b q_b inp u_a par a par b par c par d expr -di_a-a*i_a+b*c_lambda_a+b*w*lambda_b+d*u_a'};...
                {'di_b i_b lambda_a lambda_b q_a inp u_b par a par b par c par d  expr -di_b-a*i_b+b*c*lambda_b+b*w*lambda_a+d*u_b'};...
                {'dlambda_a i_a lambda_a lambda_b w par L_M par c expr -dlambda_a+L_M*c*i_a-c*lambda_a-w*lambda_b'};...
                {'dlambda_b i_b lambda_b w lambda_a par L_M par c expr -dlambda_b+L_M*c*i_b-c*lambda_b-w*lambda_a'};...
                {'dw w i_a lambda_b i_b lambda_a inp Tl par k par c_f par c_t expr -dw-k*c_f*w+k*c_t*(i_a*lambda_b-i_b*lambda_a)-k*Tl'};...
                ];
            
            der = [...
                {'int di_a dot i_a expr differentiator'};...
                {'int di_b dot i_b expr differentiator'};...
                {'int dlambda_a dot lambda_a expr differentiator'};...
                {'int dlambda_b dot lambda_b expr differentiator'};...
                {'int dw dot w expr differentiator'};...
                ];
            
            msr = [...
                {'fault msr i_a_m i_a expr -i_a_m+i_a'};...
                {'fault msr i_b_m i_b expr -i_b_m+i_b'};...
                {'fault msr w_m w expr -w_m+w'};...
                ];
                
            this.constraints = [...
                {con},{'c'};...
                {der},{'d'};...
                {msr},{'s'};...
                ];
            
            this.coordinates = [];
            
        end
        
    end
    
end