classdef g005a < model
    %% UAV model described in
    %Fravolini, M., Campa, G., & Napolitano, M. (2008).
    %Design of Redundancy Relations for Unmanned Aerial Vehicle FDI.
    %AIAA Guidance, Navigation and Control Conference and Exhibit, (August), 1–12.
    %Retrieved from http://arc.aiaa.org/doi/abs/10.2514/6.2008-7421
    
    methods
        function this = g005a()
            this.name = 'g005a';
            this.description = 'UAV model from "Design of Redundancy Relations for Unmanned Aerial Vehicle FDI, modified to produce less MTESs"';
            
            kin = [...
                {'dot_V ni a ni b Fx ni Fy ni Fz'};...
                {'dot_a ni a ni b ni V q ni p ni r ni Fx Fz'};...
                {'dot_b ni a ni b ni V ni p r ni Fx Fy ni Fz'};...
                {'dot_p ni p ni q ni r L N'};...
                {'dot_q ni p ni r M'};...
                {'dot_r ni p ni q ni r L N'};...
                {'dot_psi ni phi ni q r ni theta'};...
                {'dot_theta q ni phi ni r'};...
                {'dot_phi p ni phi ni theta ni r ni q'};...
                {'dot_h ni u ni theta ni v ni phi ni w'};...
                ];
            
            der = [...
                {'int dot_V dot V'};...
                {'int dot_a dot a'};...
                {'int dot_b dot b'};...
                {'int dot_p dot p'};...
                {'int dot_q dot q'};...
                {'int dot_r dot r'};...
                {'int dot_phi dot phi'};...
                {'int dot_theta dot theta'};...
                {'int dot_psi dot psi'};...
                {'int dot_h dot h'};...
                ];
            
            dyn = [...
                {'Xa ni V a de'};...
                {'Ya ni V ni b ni p ni r ni da ni dr'};...
                {'Za ni V ni a ni q ni de'};...
                {'La ni V ni b ni p ni r ni da ni dr'};...
                {'Ma ni V ni a ni q ni de'};...
                {'Na ni V ni b ni p ni r ni da ni dr'};...
                {'Xgr theta'};...
                {'Ygr ni theta phi'};...
                {'Zgr theta phi'};...
                {'Fx Xa Xt Xgr'};...
                {'Fy Ya Ygr'};...
                {'Fz Za Zgr'};...
                {'L La'};...
                {'M Ma'};...
                {'N Na'};...
                {'V u a b'};...
                {'ni V v a'};...
                {'ni V w a ni b'};...
                ];
            
            msr = [...
                {'fault Xt inp Xt_c'};...
                {'fault da inp da_c'};...
                {'fault de inp de_c'};...
                {'fault dr inp dr_c'};...
                {'fault V msr V_m'};...
                {'fault a msr a_m'};...
                {'fault b msr b_m'};...
                {'p msr p_m'};...
                {'q msr q_m'};...
                {'r msr r_m'};...
                {'psi msr psi_m'};...
                {'theta msr theta_m'};...
                {'phi msr phi_m'};...
                {'fault h msr h_m'};...
                ];
            
            this.constraints = [...
                {kin},{'k'};...
                {der},{'d'};...
                {dyn},{'f'};...
                {msr},{'s'};...
                ];
            
            this.coordinates = [];
            
        end
        
    end
    
end
