classdef g033 < model
    
    methods
        function this = g033()
            this.name = 'g033';
            this.description = 'Ardupilot MAVLink model';
            
            %% Equation list
            % legend:
            % dot - differential relation
            % int - integral term
            % trig - trigonometric term
            % ni - general non-invertible term
            % inp - input variable
            % out - output variable % NOT SUPPORTED
            % msr - measured variable
            % sub - subsystem where the equation belongs
            kin = [...
                {'Beta v Va expr -v+sin(Beta)*Va'};...
                ];
            
            der = [...
                {'int dot_v dot v expr differentiator'};...
                ];
            
            dyn = [...
                ];
            
%             % Add all MAVLink messages info
%             msg_id, msg_name
            msr = [...
%             0, HEARTBEAT
%             1, SYS_STATUS
                {'msr load_sys_status load sub autopilot expr equal'};...
                {'msr voltage_battery_sys_status voltage_battery sub autopilot expr equal'};...
                {'msr current_battery_sys_status current_battery sub autopilot expr equal'};...
                {'msr drop_rate_comm_sys_status drop_rate_comm sub autopilot expr equal'};...
                {''};...
%             2, SYSTEM_TIME
%             24, GPS_RAW_INT
                {'msr gps_fix_type_gps_raw_int gps_fix_type sub sensors expr equal'};...
                {'msr latitude_gps_raw_int latitude sub sensors expr equal'};...
                {'msr longitude_gps_raw_int longitude sub sensors expr equal'};...
                {'msr alt_msl_gps_raw_int alt_msl sub sensors expr equal'};...
                {'msr eph_gps_raw_int sub eph sensors expr equal'};...
                {'msr epv_gps_raw_int sub epv sensors expr equal'};...
                {'msr v_ground_gps_raw_int v_ground sub sensors expr equal'};...
                {'msr cog_gps_raw_int cog sub sensors expr equal'};...
                {'msr satellites_gps_raw_int satellites sub sensors expr equal'};...
%             25, GPS_STATUS
%             26, SCALED_IMU
%             27, RAW_IMU % This is problematic because it depends on which
%             IMU is active
%                 {'msr a_x_raw_imu a_x'};...
%                 {'msr a_y_raw_imu a_y'};...
%                 {'msr a_z_raw_imu a_z'};...
%                 {'msr p_raw_imu p'};...
%                 {'msr q_raw_imu q'};...
%                 {'msr r_raw_imu r'};...
%                 {'msr h_x_raw_imu h_x'};...
%                 {'msr h_y_raw_imu h_y'};...
%                 {'msr h_z_raw_imu h_z'};...
%             28, RAW_PRESSURE
%             29, SCALED_PRESSURE
                {'msr press_abs_scaled_pressure press_abs sub sensors expr equal'};...
                {'msr press_diff_scaled_pressure press_diff sub sensors expr equal'};...
                {'msr temperature_scaled_pressure temperature sub sensors expr equal'};...
%             30, ATTITUDE
                {'msr roll_attitude roll sub navigation expr equal'};...
                {'msr pitch_attitude pitch sub navigation expr equal'};...
                {'msr yaw_attitude yaw sub navigation expr equal'};...
                {'msr p_attitude p sub navigation expr equal'};...
                {'msr q_attitude q sub navigation expr equal'};...
                {'msr r_attitude r sub navigation expr equal'};...
%             31, ATTITUDE_QUATERNION
%             32, LOCAL_POSITION_NED
                {'msr p_n_local_position_ned p_n sub navigation expr equal'};...
                {'msr p_e_local_position_ned p_e sub navigation expr equal'};...
                {'msr p_d_local_position_ned p_d sub navigation expr equal'};...
                {'msr v_n_local_position_ned v_n sub navigation expr equal'};...
                {'msr v_e_local_position_ned v_e sub navigation expr equal'};...
                {'msr v_d_local_position_ned v_d sub navigation expr equal'};...
%             33, GLOBAL_POSITION_INT
                {'msr latitude_global_position_int latitude sub navigation expr equal'};...
                {'msr longitude_global_position_int longitude sub navigation expr equal'};...
                {'msr alt_msl_global_position_int alt_msl sub navigation expr equal'};...
                {'msr alt_agl_global_position_int alt_agl sub navigation expr equal'};...
                {'msr v_n_global_position_int v_n sub navigation expr equal'};...
                {'msr v_e_global_position_int v_e sub navigation expr equal'};...
                {'msr v_d_global_position_int v_d sub navigation expr equal'};...
                {'msr yaw_global_position_int yaw sub navigation expr equal'};...
%             34, RC_CHANNELS_SCALED
%             35, RC_CHANNELS_RAW
%                 {''};...
%             36, SERVO_OUTPUT_RAW
%                 {''};...
%             49, GPS_GLOBAL_ORIGIN
%             61, ATTITUDE_QUATERNION_COV
%             62, NAV_CONTROLLER_OUTPUT
                {'msr roll_c_nav_controller_output roll_c sub autopilot expr equal'};...
                {'msr pitch_c_nav_controller_output pitch_c sub autopilot expr equal'};...
                {'msr yaw_c_nav_controller_output yaw_c sub autopilot expr equal'};...
                {'msr bearing_target_nav_controller_output bearing_target sub autopilot expr equal'};...
                {'msr dist_wp_nav_controller_output dist_wp sub autopilot expr equal'};...
                {'msr error_alt_nav_controller_output error_alt sub autopilot expr equal'};...
                {'msr error_v_air_nav_controller_output error_v_air sub autopilot expr equal'};...
                {'msr error_xtrack_nav_controller_output error_xtrack sub autopilot expr equal'};...
%             63, GLOBAL_POSITION_INT_COV
%             64, LOCAL_POSITION_NED_COV
%             65, RC_CHANNELS
%                 {''};...
%             74, VFR_HUD
                {'msr v_air_vhr_hud v_air sub navigation expr equal'};...
                {'msr v_ground_vhf_hud v_ground sub navigation expr equal'};...
                {'msr yaw_vfr_hud yaw sub navigation expr equal'};...
                {'msr throttle_out_vfr_hud throttle_out sub navigation expr equal'};...
                {'msr alt_msl_vfr_hud alt_ms sub navigation expr equal'};...
                {'msr climb_vfr_hud climb sub navigation expr equal'};...
%             100, OPTICAL_FLOW
%             101, GLOBAL_VISION_POSITION_ESTIMATE
%             102, VISION_POSITION_ESTIMATE
%             103, VISION_SPEED_ESTIMATE
%             104, VICON_POSITION_ESTIMATE
%             105, HIGHRES_IMU
%             106, OPTICAL_FLOW_RAD
%             111, TIMESYNC
%             116, SCALED_IMU2
                {'msr a_x_scaled_imu2 a_x sub sensors expr equal'};...
                {'msr a_y_scaled_imu2 a_y sub sensors expr equal'};...
                {'msr a_z_scaled_imu2 a_z sub sensors expr equal'};...
                {'msr p_scaled_imu2 p sub sensors expr equal'};...
                {'msr q_scaled_imu2 q sub sensors expr equal'};...
                {'msr r_scaled_imu2 r sub sensors expr equal'};...
                {'msr h_x_scaled_imu2 h_x sub sensors expr equal'};...
                {'msr h_y_scaled_imu2 h_y sub sensors expr equal'};...
                {'msr h_z_scaled_imu2 h_z sub sensors expr equal'};...
%             124, GPS2_RAW
%             125, POWER_STATUS
                {'msr vcc_power_status vcc sub sensors expr equal'};...
                {'msr v_servo_power_status v_servo sub sensors expr equal'};...
%                 {'msr flags'};...
%             127, GPS_RTK
%             128, GPS2_RTK
%             129, SCALED_IMU3
%             132, DISTANCE_SENSOR
%             137, SCALED_PRESSURE2
%             138, ATT_POS_MOCAP
%             141, ALTITUDE
%             143, SCALED_PRESSURE3
%             146, CONTROL_SYSTEM_STATE
%             147, BATTERY_STATUS
%             150, SENSOR_OFFSETS % This is problematic because it depends on which
%             IMU, barometer and INS is active is active
%                 {''};...
%             152, MEMINFO
                {'msr freemem_meminfo freemem sub os expr equal'};...
%             153, AP_ADC
%             163, AHRS
                {'msr error_rp_ahrs_ahrs error_rp_ahrs sub navigation expr equal'};...
                {'msr error_yaw_ahrs_ahrs error_yaw_ahrs sub navigation expr equal'};...
%             165, HWSTATUS
                {'msr vcc_hwstatus vcc expr equal'};...
%             167, LIMITS_STATUS
%             168, WIND
                {'msr dir_wind_wind dir_wind sub navigation expr equal'};...
                {'msr v_wind_hor_wind v_wind_hor sub navigation expr equal'};...
                {'msr v_wind_vert_wind v_wind_vert sub navigation expr equal'};...
%             173, RANGEFINDER
%             174, AIRSPEED_AUTOCAL
                {'msr ratio_v_air_airspeed_autocal ratio_v_air sub autopilot expr equal'};...
%             178, AHRS2
                {'msr roll_ahrs2 roll sub navigation expr equal'};...
                {'msr pitch_ahrs2 pitch sub navigation expr equal'};...
                {'msr yaw_ahrs2 yaw sub navigation expr equal'};...
                {'msr alt_msl_ahrs2 alt_msl sub navigation expr equal'};...
                {'msr latitude_ahrs2 latitude sub navigation expr equal'};...
                {'msr longitude_ahrs2 longitude sub navigation expr equal'};...
%             181, BATTERY2
%             182, AHRS3
                {'msr roll_ahrs3 roll sub navigation expr equal'};...
                {'msr pitch_ahrs3 pitch sub navigation expr equal'};...
                {'msr yaw_ahrs3 yaw sub navigation expr equal'};...
                {'msr alt_msl_ahrs3 alt_msl sub navigation expr equal'};...
                {'msr latitude_ahrs3 latitude sub navigation expr equal'};...
                {'msr longitude_ahrs3 longitude sub navigation expr equal'};...
%             191, MAG_CAL_PROGRESS
%             192, MAG_CAL_REPORT
%             193, EKF_STATUS_REPORT % This is problematic because it depends on which
%             AHRS is active
%                 {''};...
%             194, PID_TUNING
%             226, RPM
%             230, ESTIMATOR_STATUS
%             231, WIND_COV
%             232, GPS_INPUT
%             234, HIGH_LATENCY
%             241, VIBRATION
                {'msr vibration_x_vibration vibration_x sub sensors expr equal'};...
                {'msr vibration_y_vibration vibration_y sub sensors expr equal'};...
                {'msr vibration_z_vibration vibration_z sub sensors expr equal'};...
%             246, ADSB_VEHICLE
%             247, COLLISION
                ];
            
            this.constraints = [...
                {kin},{'k'};...
                {der},{'d'};...
                {dyn},{'f'};...
                {msr},{'s'};...
                ];            
        end
        
    end
    
end