function [ constraints, coords ] = g008( )
%% Three-tank system as presented on:
% Frisk, E., Bregon, A., Aslund, J., Krysander, M., Pulido, B., & Biswas, G. (2012).
% Diagnosability Analysis Considering Causal Interpretations for Differential Constraints.
% IEEE Transactions on Systems, Man, and Cybernetics - Part A: Systems and Humans, 42(5), 1216–1229. doi:10.1109/TSMCA.2012.2189877


con = [...
    {'q1 p1 p2'};...
    {'q2 p2 p3'};...
    {'q3 p3'};...
    {'p1_dot q0 q1'};...
    {'p2_dot q1 q2'};...
    {'p3_dot q2 q3'};...
    ];

der = [...
    {'int p1 dot p1_dot'};...
    {'int p2 dot p2_dot'};...
    {'int p3 dot p3_dot'};...
    ];

msr = [...
    {'msr y1 p1'};...
    {'msr y2 q2'};...
    {'msr y3 q0'};...
    ];

constraints = [...
    {con},{'c'};...
    {der},{'d'};...
    {msr},{'s'};...
    ];

coords = [];


end