function [ constraints, name, coords ] = g012()
%% Roll model
% Found in
% R. Beard Book, p.90

name = 'Linearized roll model found in R. Beard book, p.90';

con = [...
    {'fault b_dot b p r phi inp deltaa inp deltar'};...
    {'fault p_dot b p r inp deltaa inp deltar'};...
    {'fault r_dot b p r inp deltaa inp deltar'};...
    {'phi_dot p'};...
    ];

der = [...
    {'int b_dot dot b'};...
    {'int p_dot dot p'};...
    {'int r_dot dot r'};...
    {'int phi_dot dot phi'};...
    ];

msr = [...
    {'fault msr y1 p'};...
    {'fault msr y2 r'};...
%     {'fault msr y5 Va'};...
%     {'fault msr y6 a'};...
    ];

constraints = [...
    {con},{'c'};...
    {der},{'d'};...
    {msr},{'s'};...
    ];

coords = [];


end

