function [ constraints, name, coords ] = g013()
%% Example UAV model
% Presented in my paper

name = 'Example non-linear UAV longitudinal model';

con = [...
    {'fault u_dot u w q theta inp deltae inp deltat'};...
    {'fault w_dot u w q theta inp deltae'};...
    {'fault q_dot u w q inp deltae'};...
    {'theta_dot q'};...
    {'h_dot u w theta'};...
    {'dgr h hgr'};...
    ];

der = [...
    {'int u_dot dot u'};...
    {'int w_dot dot w'};...
    {'int q_dot dot q'};...
    {'int theta_dot dot theta'};...
    {'int h_dot dot h'};...
    ];

msr = [...
    {'fault msr y1 q'};...
    {'fault msr y2 theta'};...
    ];

constraints = [...
    {con},{'c'};...
    {der},{'d'};...
    {msr},{'s'};...
    ];

coords = [];


end

