function [constraints, name, coords] = g014()

%% Structural Model Creation
% Fixed Wing UAV

name = 'Fixed-wing UAV model';

%% Equation list
% legend:
% dot - differential relation
% int - integral term
% trig - trigonometric term
% ni - general non-invertible term
% inp - input variable % NOT SUPPORTED
% out - output variable % NOT SUPPORTED
% msr - measured variable

%% Kinematic Equations

% Position derivatives
kin = [...
    {'Dnorth phi theta psi u v w'};...
	{'Deast phi theta psi u v w'};...
	{'Ddown phi theta psi u v w'};
    {'chi Deast Dnorth'};... % Course angle
];

der = [...
    {'int Dnorth dot north'};...
    {'int Deast dot east'};...
    {'int Ddown dot down'};
];

% Euler angle derivatives
kin = [kin;...
    {'Dphi phi theta p q r'};...
    {'Dtheta phi q r'};...
    {'Dpsi phi theta q r'}
];

der = [der;...
    {'int Dphi dot phi'};...
    {'int Dtheta dot theta'};...
    {'int Dpsi dot psi'};...
];

% Angular Velocity
kin = [kin;...
    {'fault Dp Γ Jxz Jx Jy Jz p q r Tx Tz'};...
    {'fault Dq Jy Jz Jxz p r Ty'};...
    {'fault Dr Γ Jx Jy Jz Jxz p q r Tx Tz'};...
    {'fault Γ Jx Jz Jxz'};...
];

der = [der;...
    {'int Dp dot p'};...
    {'int Dq dot q'};...
    {'int Dr dot r'};...
];

% Linear Velocity
kin = [kin;...
    {'Du v w r q Fx m'};...
    {'Dv u w p r Fy m'};...
    {'Dw u v p q Fz m'};...
];

der = [der;...
    {'int Du dot u'};...
    {'int Dv dot v'};...
    {'int Dw dot w'};...
];

% Air data
kin = [kin;...
    {'ur u uw'};...
    {'vr v vw'};...
    {'wr w ww'};...
    {'ww'};... %Assumption ww = 0;
    {'alpha wr ur'};...
    {'beta ur Va'};...
    {'Va ni ur ni vr ni wr'};...
];

% Mass Distribution
kin = [kin;...
    {'m mnom merr'};...
    {'pcgx pnomx m perrx merr'};...
    {'pcgy pnomy m perry merr'};...
    {'pcgz pnomz m perrz merr'};...
    {'merr'};... % merr = 0;
];

%% Dynamic Equations
dyn = [];

dyn = [dyn;...
    {'Fx Fgx Fax Ftx'};...
    {'Fy Fgy Fay Fty'};...
    {'Fz Fgz Faz Ftz'};...
    {'Tx Tgx Tax Ttx'};...
    {'Ty Tgy Tay Tty'};...
    {'Tz Tgz Taz Ttz'};...
];

% Gravity
dyn = [dyn;...
    {'Fgx theta m g'};...
    {'Fgy phi theta m g'};...
    {'Fgz phi theta m g'};...
];

% Aerodynamics
dyn = [dyn;...
    {'Fax alpha beta FD FY FL'};...
    {'Fay beta FD FY'};...
    {'Faz alpha beta FD FY FL'};...
    {'Taxt Taxt pcgy pcgz pcly pclz Fay Faz'};...
    {'Tayt Tayt pcgx pcgz pclx pclz Fax Faz'};...
    {'Tazt Tazt pcgx pcgy pclx pcly Fax Fay'};...
    {'qbar rho Va'};...
    {'fault FD qbar S CD'};...
    {'fault FY qbar S CY'};...
    {'fault FL qbar S CL'};...
    {'fault Tax qbar S b Cl'};...
    {'fault Tay qbar S c Cm'};...
    {'fault Taz qbar S b Cn'};...
    {'fault CD ni Va ni alpha ni q ni deltae'};...
    {'fault CY ni Va ni beta ni p ni r ni deltaa ni deltar'};...
    {'fault CL ni Va ni alpha ni ni q ni deltae'};...
    {'fault Cl ni Va ni beta ni p ni r ni deltaa ni deltar'};...
    {'fault Cm ni Va ni alpha ni q ni deltae'};...
    {'fault Cn ni Va ni beta ni p ni r ni deltaa ni deltar'};...
];

% Propeller
dyn = [dyn;...
    {'fault Fty'};...
    {'fault Ftz'};...
    {'Ttxt Ttx pcgy pcgz ppry pprz Ftx Ftz'};...
    {'Ttyt Tty pcgx pcgz pprx pprz Ftx Ftz'};...
    {'Ttzt Ttz pcgx pcgy pprx ppry Ftx Fty'};...
    {'fault Tty'};...
    {'fault Ttz'};...
    {'fault Ftx CT rho n'};...
    {'fault CT ni Jar'};...
    {'Jar Va n'};...
    {'fault Pp Cp rho n'};...
    {'fault Cp ni Jar'};...
    {'fault Dn Pe Pp n'};...
    {'Ttx Pp n'};...
 ];   
    
der = [der;...
    {'int Dn dot n'};...
];

% Motor
dyn = [dyn;...
    {'fault n Kv Ei'};...
    {'fault Ei Vin Im Rm'};...
    {'Pe Ei Ii'};...
    {'fault Ii Im Io Ei R1'};...
    {'Pin Vin Im'};...
    {'fault Vin Vbat Io Rbat Rs deltat'};...
];

%% Other models

mod = [];

mod = [mod;...
    {'H down'};... % geopotential altitude
    {'temp temp0 H H0'};... % Temperature gradient
    {'P P0 temp0 temp'};... % Pressure gradient
    {'rho P temp'};... % density gradient
    {'Pt P rho Va'};... % dynamic pressure
];

%% Sensory equations

msr = [];

msr = [msr;...
    {'fault msr amx Fx m g theta'};... % Acceleration
    {'fault msr amy Fy m g phi theta'};...
    {'fault msr amz Fz m g phi theta'};...
    {'fault msr pm p'};... % Angular velocity
    {'fault msr qm q'};...
    {'fault msr rm r'};...
    {'fault msr hmx hx'};... % Magnetic field
    {'fault msr hmy hy'};...
    {'fault msr hmz hz'};...
    {'fault msr phim phi'};... % Euler angles
    {'fault msr thetam theta'};...
    {'fault msr psim psi'};...
    {'fault msr northm north'};... % GPS measurements
    {'fault msr eastm east'};...
    {'fault msr downm down'};...
    {'fault msr Dnorthm Dnorth'};...
    {'fault msr Deastm Deast'};...
    {'fault msr chim chi'};...
    {'fault msr temp0'};... % Initialization temperature
    {'fault msr H0'};... % Initialization altitude
    {'fault msr Pm P'};... % Barometer reading
    {'fault msr tempm temp'};... % Therometer reading
    {'fault msr Ptm Pt'};... % Pitot reading
    {'fault msr alpham alpha'};.... % AoA reading
    {'fault msr betam beta'};... % AoS reading
    {'fault msr downml down'};... % Range finder reading
    {'fault msr Vbatm Vbat Io Rbat'};... % Battery voltage measurement
    {'fault msr Iom Io'};... % Battery current measurement
    {'fault msr nm n'};... % Motor rps measurement
];


%% Summing up
constraints = [...
    {kin},{'k'};...
    {dyn},{'f'};...
    {der},{'d'};...
    {mod},{'m'};...
    {msr},{'s'};...
    ];

%% Specifying node coordinates if available
coords = [];

end