function [constraints, coords] = modelFile()

%% Structural Model Creation
% Fixed Wing UAV

%% Equation list
% legend:
% dot - differential relation
% int - integral term
% trig - trigonometric term
% ni - general non-invertible term
% inp - input variable % NOT SUPPORTED
% out - output variable % NOT SUPPORTED
% msr - measured variable

%% Kinematic Equations

% Position derivatives
kin = [...
    {'Dnorth phi theta psi u v w'};...
	{'Deast phi theta psi u v w'};...
	{'Ddown phi theta psi u v w'};
    {'chi Deast Dnorth'};... % Course angle
];

der = [...
    {'int Dnorth dot north'};...
    {'int Deast dot east'};...
    {'int Ddown dot down'};
];

% Euler angle derivatives
kin = [kin;...
    {'Dphi phi theta p q r'};...
    {'Dtheta phi q r'};...
    {'Dpsi phi theta q r'}
];

der = [der;...
    {'int Dphi dot phi'};...
    {'int Dtheta dot theta'};...
    {'int Dpsi dot psi'};...
];

% Angular Velocity
kin = [kin;...
    {'Dp Γ Jxz Jx Jy Jz p q r Tx Tz'};...
    {'Dq Jy Jz Jxz p r Ty'};...
    {'Dr Γ Jx Jy Jz Jxz p q r Tx Tz'};...
    {'Γ Jx Jz Jxz'};...
];

der = [der;...
    {'int Dp dot p'};...
    {'int Dq dot q'};...
    {'int Dr dot r'};...
];

% Linear Velocity
kin = [kin;...
    {'Du v w r q Fx m'};...
    {'Dv u w p r Fy m'};...
    {'Dw u v p q Fz m'};...
];

der = [der;...
    {'int Du dot u'};...
    {'int Dv dot v'};...
    {'int Dw dot w'};...
];

% Air data
kin = [kin;...
    {'ur u uw'};...
    {'vr v vw'};...
    {'wr w ww'};...
    {'ww'};... %Assumption ww = 0;
    {'alpha wr ur'};...
    {'beta ur Va'};...
    {'Va ni ur ni vr ni wr'};...
];

% Mass Distribution
kin = [kin;...
    {'m mnom merr'};...
    {'pcgx m perrx merr'};...
    {'pcgy m perry merr'};...
    {'pcgz m perrz merr'};...
];

%% Dynamic Equations
dyn = [];

dyn = [dyn;...
    {'Fx Fgx Fax Ftx'};...
    {'Fy Fgy Fay Fty'};...
    {'Fz Fgz Faz Ftz'};...
    {'Tx Tgx Tax Ttx'};...
    {'Ty Tgy Tay Tty'};...
    {'Tz Tgz Taz Ttz'};...
];

% Gravity
dyn = [dyn;...
    {'Fgx theta m g'};...
    {'Fgy phi theta m g'};...
    {'Fgz phi theta m g'};...
];

% Aerodynamics
dyn = [dyn;...
    {'Fax alpha beta FD FY FL'};...
    {'Fay beta FD FY'};...
    {'Faz alpha beta FD FY FL'};...
    {'Taxt Taxt pcgy pcgz pcly pclz Fay Faz'};...
    {'Tayt Tayt pcgx pcgz pclx pclz Fax Faz'};...
    {'Tazt Tazt pcgx pcgy pclx pcly Fax Fay'};...
    {'qbar rho Va'};...
    {'FD qbar S CD'};...
    {'FY qbar S CY'};...
    {'FL qbar S CL'};...
    {'Tax qbar S b Cl'};...
    {'Tay qbar S c Cm'};...
    {'Taz qbar S b Cn'};...
    {'CD ni Va ni alpha ni q ni deltae'};...
    {'CY ni Va ni beta ni p ni r ni deltaa ni deltar'};...
    {'CL ni Va ni alpha ni ni q ni deltae'};...
    {'Cl ni Va ni beta ni p ni r ni deltaa ni deltar'};...
    {'Cm ni Va ni alpha ni q ni deltae'};...
    {'Cn ni Va ni beta ni p ni r ni deltaa ni deltar'};...
];

% Propeller
dyn = [dyn;...
    {'Fty'};...
    {'Ftz'};...
    {'Ttxt Ttx pcgy pcgz ppry pprz Ftx Ftz'};...
    {'Ttyt Tty pcgx pcgz pprx pprz Ftx Ftz'};...
    {'Ttzt Ttz pcgx pcgy pprx ppry Ftx Fty'};...
    {'Tty'};...
    {'Ttz'};...
    {'Ftx CT rho n'};...
    {'CT ni Jar'};...
    {'Jar Va n'};...
    {'Pp Cp rho n'};...
    {'Cp ni Jar'};...
    {'Dn Pe Pp n'};...
    {'Ttx Pp n'};...
 ];   
    
der = [der;...
    {'int Dn dot n'};...
];

% Motor
dyn = [dyn;...
    {'n Kv Ei'};...
    {'Ei Vin Im Rm'};...
    {'Pe Ei Ii'};...
    {'Ii Im Io Ei R1'};...
    {'Pin Vin Im'};...
    {'Vin Vbat Io Rbat Rs deltat'};...
];

%% Other models

mod = [];

mod = [mod;...
    {'H down'};... % geopotential altitude
    {'temp temp0 H H0'};... % Temperature gradient
    {'P P0 temp0 temp'};... % Pressure gradient
    {'rho P temp'};... % density gradient
    {'Pt P rho Va'};... % dynamic pressure
];

%% Sensory equations

msr = [];

msr = [msr;...
    {'msr amx Fx m g theta'};... % Acceleration
    {'msr amy Fy m g phi theta'};...
    {'msr amz Fz m g phi theta'};...
    {'msr pm p'};... % Angular velocity
    {'msr qm q'};...
    {'msr rm r'};...
    {'msr hmx hx'};... % Magnetic field
    {'msr hmy hy'};...
    {'msr hmz hz'};...
    {'msr phim phi'};... % Euler angles
    {'msr thetam theta'};...
    {'msr psim psi'};...
    {'msr northm north'};... % GPS measurements
    {'msr eastm east'};...
    {'msr downm down'};...
    {'msr Dnorthm Dnorth'};...
    {'msr Deastm Deast'};...
    {'msr chim chi'};...
    {'msr temp0'};... % Initialization temperature
    {'msr H0'};... % Initialization altitude
    {'msr Pm P'};... % Barometer reading
    {'msr tempm temp'};... % Therometer reading
    {'msr Ptm Pt'};... % Pitot reading
    {'msr alpham alpha'};.... % AoA reading
    {'msr betam beta'};... % AoS reading
    {'msr downml down'};... % Range finder reading
    {'msr Vbatm Vbat Io Rbat'};... % Battery voltage measurement
    {'msr Iom Io'};... % Battery current measurement
    {'msr nm n'};... % Motor rps measurement
];


%% Summing up
constraints = [...
    {kin},{'k'};...
    {dyn},{'f'};...
    {der},{'d'};...
    {mod},{'m'};...
    {msr},{'s'};...
    ];

%% Specifying node coordinates if available
coords = [];

end