classdef g037 < model
    
    methods
        function this = g037()
            this.name = 'g037';
            this.description = 'Overconstrained spring-mass model for which Pantelide''s algorithm can''t reduce index in Openmodelica';
            
            %% Equation list
            % legend:
            % dot - differential relation
            % int - integral term
            % trig - trigonometric term
            % ni - general non-invertible term
            % inp - input variable
            % out - output variable % NOT SUPPORTED
            % msr - measured variable
            % sub - subsystem where the equation belongs
            kin = [...
                {'roof_flange_s'};...
                {'forceStep1_s_support'};...
                {'forceStep1_f'};...
                {'forceStep1_s forceStep1_flange_s forceStep1_s_support'};...
                {'myPositionSensor1_flange_f'};...
                {'myPositionSensor1_flange_s'};...
                {'mass1_flange_a_s myPositionSensor1_flange_s'};...
                {'spring1_flange_b_f spring1_f'};...
                {'spring1_flange_a_f spring1_f'};...
                {'mass1_v mass1_ds'};...
                {'mass1_a mass1_dv'};...
                {'forceStep1_f forceStep1_flange_f'};...
                {'mass1_flange_a_s spring1_flange_b_s'};...
                {'forceStep1_flange_s mass1_flange_b_s'};...
                {'roof_flange_s spring1_flange_a_s'};...
                {'spring1_s_rel spring1_flange_b_s spring1_flange_a_s'};...
                {'fault spring1_f spring1_s_rel'};...
                {'mass1_a mass1_flange_a_f mass1_flange_b_f'};...
                {'mass1_flange_a_s mass1_s'};...
                {'mass1_flange_b_s mass1_s'};...
                {'roof_flange_f spring1_flange_a_f'};...
                {'spring1_flange_b_f mass1_flange_a_f myPositionSensor1_flange_f'};...
                {'mass1_flange_b_f forceStep1_flange_f'};...
                ];
            
            der = [...
                {'int mass1_ds dot mass1_s'};...
                {'int mass1_dv dot mass1_v'};...
                ];
            
            dyn = [...
                ];
            % Set non-zero V, u
            
            msr = [...
                ];
            
            this.constraints = [...
                {kin},{'k'};...
                {der},{'d'};...
                {dyn},{'f'};...
                {msr},{'s'};...
                ];            
        end
        
    end
    
end