classdef g008 < model
% Benchmark Three-tank system, taken from Fault Diagnosis Toolbox
    methods
        function this = g008()
            this.name = 'g008';
            this.description = 'Three-tank system';
            % As presented on:
            % Frisk, E., Bregon, A., Aslund, J., Krysander, M., Pulido, B., & Biswas, G. (2012).
            % Diagnosability Analysis Considering Causal Interpretations for Differential Constraints.
            % IEEE Transactions on Systems, Man, and Cybernetics - Part A: Systems and Humans, 42(5), 1216–1229. doi:10.1109/TSMCA.2012.2189877
            
            %   q1==1/Rv1*(p1-p2) + fV1,...
            %   q2==1/Rv2*(p2-p3) + fV2, ...
            %   q3==1/Rv3*p3 + fV3,...
            %   dp1==1/CT1*(q0-q1) + fT1,...
            %   dp2==1/CT2*(q1-q2) + fT2, ...
            %   dp3==1/CT3*(q2-q3) + fT3, ...
            %   y1==p1, y2==q2, y3==q0,...
  
            con = [...
                {'fault q1 p1 p2 par Rv1 expr -q1+1/Rv1*(p1-p2)'};...
                {'fault q2 p2 p3 par Rv2 expr -q2+1/Rv2*(p2-p3)'};...
                {'fault q3 p3 par Rv3 expr -q3+1/Rv3*p3'};...
                {'fault p1_dot q0 q1 par CT1 expr -p1_dot+1/CT1*(q0-q1)'};...
                {'fault p2_dot q1 q2 par CT2 expr -p2_dot+1/CT2*(q1-q2)'};...
                {'fault p3_dot q2 q3 par CT3 expr -p3_dot+1/CT3*(q2-q3)'};...
                ];
            
            der = [...
                {'dot p1 int p1_dot expr differentiator'};...
                {'dot p2 int p2_dot expr differentiator'};...
                {'dot p3 int p3_dot expr differentiator'};...
                ];
            
            msr = [...
                {'msr y1 q1 expr -y1+q1'};...
                {'msr y2 q2 expr -y2+q2'};...
                {'msr y3 q0 expr -y3+q3'};...
                ];
            
            this.constraints = [...
                {con},{'c'};...
                {der},{'d'};...
                {msr},{'s'};...
                ];
            
            this.coordinates = [];
        end
        
    end
    
end
