classdef g039 < model
    
    methods
        function this = g039()
            this.name = 'g039';
            this.description = ['Monitorable system from V. Flaugergues, V. Cocquempot, M. Bayart, and M. Pengov, Structural Analysis for FDI: a modified'...
            'invertibility-based canonical decomposition, in Proceedings of the 20th International Workshop on'...
            'Principles of Diagnosis, DX09, 2009, pp. 59–66.'];
            
            %% Equation list
            % legend:
            % dot - differential relation
            % int - integral term
            % trig - trigonometric term
            % ni - general non-invertible term
            % inp - input variable
            % out - output variable % NOT SUPPORTED
            % msr - measured variable
            % sub - subsystem where the equation belongs
            % mat - matrix variable
            % expr - algebraic expression
            % par - parameter
            % dist - disturbance
            % rg - residual generator
            kin = [...
                {'fault x1 inp u'};...
                {'x1 ni x2'};...
                {'x2 x3'};...
                {'x3 x4'};...
                {'ni x4 x5'};...
                {'x5 x6'};...
                {'fault msr y1 ni x6'};...
                {'fault msr y2 x6'};...
                {'x3 x7'};...
                ];
            
            der = [...
                ];
            
            msr = [...
                ];
            
            this.constraints = [...
                {kin},{'k'};...
                {der},{'d'};...
                {msr},{'s'};...
                ];            
        end
        
    end
    
end